import React from "react";

export const Vehicules = [
  "Voitures",
  "Motos",
  "Pièces et accessoires véhicules",
  "Bateaux",
  "Remorques et Caravanes",
  "Engins Agricole",
  "Engins BTP",
  "Camions",
  "Autres",
];
export const Immobiliers = [
  "Appartements",
  "Miasons & Villas",
  "Locations & Vacances",
  "Bureaux & Plateaux",
  "Remorques et Caravanes",
  "Magazins & Locaux de commerce",
  "Autres",
];
export const Informatique = [
  "Téléphones",
  "Image & Sons",
  "Ordinateurs Portables",
  "Accessoires Informatiques",
  "Jeux vidéo & Consoles",
  "Appareiles photo & Caméra",
  "Tablettes",
  "Télévisions",
  "Autres",
];
export const Maison = [
  "Electroménager & Vaisselles",
  "Meubles & décoration",
  "Jardin & Outils de bricolage",
];
export const Autres = [];
export const Loisirs = [
  "Vélos",
  "Sports & loisirs",
  "Animaux",
  "Films, Livres & Magazins",
  "Voyages & billetterie",
  "Art & Collection",
  "Instruments de musique",
];
export const Habillement = [
  "Vetements ",
  "Chaussures ",
  "Montres & Bijoux",
  "Sacs & Accessoires",
  "Vetements pour enfant & Bébé",
  "Equipements pour enfant & bébé",
  "Produits de beauté",
];
export const categorie = [
  "Véhicules",
  "Immobiliers",
  "Pour la maison et jardin",
  "Emploi & Services",
  "Entreprises",
  "Habillement & Bien Etre",
  "Informatique & Multimedia",
  "Loisirs & Divertissement",
  "Autres",
];
export const images = [
  {
    photo: require("./images/véhicules.png"),
    titre: "Véhicules",
  },
  {
    photo: require("./images/immobiliers.png"),
    titre: "Immobiliers",
  },
  {
    photo: require("./images/maison& jardin.png"),
    titre: "Pour la maison et jardin",
  },
  {
    photo: require("./images/emploi.png"),
    titre: "Emploi & Services",
  },
  {
    photo: require("./images/entreprises.png"),
    titre: "Entreprises",
  },
  {
    photo: require("./images/habillement.png"),
    titre: "Habillement & Bien Etre",
  },
  {
    photo: require("./images/info.png"),
    titre: "Informatique & Multimedia",
  },
  {
    photo: require("./images/loisir.png"),
    titre: "Loisirs & Divertissement",
  },
];
export const Emploi = [
  "Offres d'emploi",
  "Demandes d'emploi",
  "Services",
  "Cours & Formations",
];
export const Entreprises = [
  "Business & Affaires commerciales",
  "Matériels Professionnels",
  "Stocks & vente en gros",
];
export const gouvernora = [
  "Ariana",
  "Béja",
  "Ben Arous",
  "Bizerte",
  "Cabès",
  "Gafsa",
  "Jendouba",
  "Kairouan",
  "Kasserine",
  "Kébili",
  "La Mannouba",
  "Kef",
  "Mahdia",
  "Médenine",
  "Monastir",
  "Nabeul",
  "Sfax",
  "Sidi Bouzid",
  "Siliana",
  "Sousse",
  "Tatouine",
  "Tozeur",
  "Tunis",
  "Zaghouen",
];
export const ariana = [
  "Ariana Ville",
  "Autres Villes",
  "Borj Louzir",
  "Chotrana",
  "Ennasr",
  "Ettadhamen",
  "Ghazala",
  "Jardins Elmanzah",
  "La Soukra",
  "Mnihla",
  "Raoued",
  "Sidi Thabet",
];
export const sousse = [
  "Akouda",
  "Autres Villes",
  "Bouficha",
  "Chatt mariem",
  "Enfidha",
  "Hammam Sousse",
  "Hergla",
  "Kalaa Kebira",
  "Kalaa Seghira",
  "Kantaoui",
  "Khezama",
  "Kandar",
  "M'saken",
  "Sahloul",
  "Sidi Bou Ali",
  "Sidi El Heni",
  "Sousse",
  "Sousse Jawhara",
  "Sousse Médina",
  "Sousse Riadh",
  "Sousse Sidi Abdelhamid",
  "Zaouiet Ksibet Thrayett",
];
export const beja = [
  "Amdoun",
  "Autres Villes",
  "Béja Nord",
  "Béja Sud",
  "El Ksar",
  "Goubelat",
  "Medjaz El Bab",
  "Nefza",
  "Téboursouk",
  "Testour",
  "Thibar",
];
export const manouba = [
  "Autres Villes",
  "Borj El Amri",
  "Denden",
  "Djedaida",
  "Douar Hicher",
  "El Battan",
  "Manouba",
  "Manouba Ville",
  "Menzel El Habib",
  "Mornaguia",
  "Oued Ellil",
  "Tebourba",
];
export const gafsa = [
  "Autres Villes",
  "Belkhir",
  "El Guettar",
  "Gafsa Nord",
  "Gafsa Sud",
  "Mdhila",
  "Métlaoui",
  "Oum El Araies",
  "Redayef",
  "Sened",
  "Sidi Aich",
];
export const medennine = [
  "Autres Villes",
  "Ben Gardene",
  "Beni Khedech",
  "Djerba Ajim",
  "Djerba Houmt Souk",
  "Djerba Midoun",
  "Médenine",
  "Médenine Nord",
  "Médenine Sud",
  "Sidi Makhlouf",
  "Zarzis",
];
export const kef = [
  "Autres Villes",
  "Dahmani",
  "Djerissa",
  "El Ksoour",
  "Esseres",
  "Kalaa Khasbah",
  "KAlla Senan",
  "Kef Est",
  "Kef Ouest",
  "Nebeur",
  "Sakiet Sidi Youssef",
  "Tajeurouine",
];
export const nabeul = [
  "Autres Villes",
  "Béni Khaled",
  "Béni Khiar",
  "Bou Argoub",
  "Dar Chaabane El Fehri",
  "El Haouaria",
  "El mida",
  "Grombalia",
  "Hammam Ghezzaz",
  "Hammamet",
  "Hammamet Centre",
  "Hammamet Nord",
  "Kélibia",
  "Korba",
  "Menzel Bouzalfa",
  "Menzel Temime",
  "Mrezga",
  "Nabeul",
  "Soliman",
  "Takelsa",
];
export const bizerte = [
  "Autres Villes",
  "Bizerte",
  "Bizerte Nord",
  "Bizerte Sud",
  "Djoumine",
  "Ghar El Melh",
  "Ghezala",
  "Mateur",
  "Menzel Bourghiba",
  "Menzel Jemil",
  "Ras Jebal",
  "Sejnene",
  "TInja",
  "Utique",
  "Zarzouna",
];
export const kairouane = [
  "Autres Villes",
  "Bouhajla",
  "Chebika",
  "Echarda",
  "EL Alaa",
  "El Ouslatia",
  "Haffouz",
  "Hajeb EL Ayoun",
  "Kairouan Nord",
  "Kairouan Sud",
  "Nasrallah",
  "Sbikha",
];
export const kasserine = [
  "Autres Villes",
  "Djedeliane",
  "El Ayoun",
  "Ezzouhour",
  "Fériana",
  "Foussana",
  "Hassi Ferid",
  "Hidra",
  "Kasserine Nord",
  "Kasserine Sud",
  "Majel Bel Abbes",
  "Sbeitla",
  "Sbiba",
  "Thala",
];
export const mahdia = [
  "Autres Villes",
  "Bou Merdés",
  "Chebba",
  "Chourbane",
  "El Jem",
  "Essouassi",
  "Hebira",
  "Ksour Essef",
  "Mahdia",
  "Mellouleche",
  "Ouled Chamekh",
  "Sidi Alouene",
];
export const monastir = [
  "Autres Villes",
  "Bekalta",
  "Bembla",
  "Beni Hassene",
  "Jemmal",
  "Ksar Hellal",
  "Ksibet El Mediouni",
  "Moknine",
  "Monastir",
  "Ouerdenine",
  "Sahline",
  "Sayada Lamta Bouhjar",
  "Téboulba",
  "Zéramdine",
];
export const sfax = [
  "Autres Villes",
  "Agareb",
  "Bir Ali Ben Khalifa",
  "El Amra",
  "Elhencha",
  "Ghariba",
  "Jebiniana",
  "Kekennah",
  "Mahrés",
  "Menzel Chaker",
  "Route de Gabes",
  "Route de l'aéroport",
  "Route El Afrane",
  "Route Gremda",
  "Route Manzel Chaker",
  "Route Mehdia",
  "Route Mharza",
  "Route Saltania",
  "Route Sokra",
  "Route Sokra",
  "Route Taniour",
  "Route Tunis",
  "Sakiet Eddaier",
  "Sakiet Ezzit",
  "Sfax Médina",
  "Skhira",
  "Thyna",
];
export const tatouine = [
  "Autres Villes",
  "Bir Lahmar",
  "Dehiba",
  "Ghomrassen",
  "Remada",
  "Smar",
  "Tataouine",
  "Tataouine Nord",
  "Tataouine Sud",
];
export const zagouane = [
  "Autres Villes",
  "Bir Mchargua",
  "El Fahs",
  "Ennadhour",
  "Ezzeriba",
  "Saouaf",
  "Zaghouane",
];
export const benarous = [
  "Autres Villes",
  "Ben Arous",
  "Borj Sedria",
  "Boumhel",
  "El Mourouj",
  "Ezzahra",
  "Fouchana",
  "Hammam chott",
  "Hammam Lif",
  "Medina Jedida",
  "Megrine",
  "Mohamdia",
  "Mornag",
  "Rades",
];
export const gabès = [
  "Autres Villes",
  "El Hamma",
  "Gabès Medina",
  "Gabès Ouest",
  "Gabès Sud",
  "Ghannouch",
  "Mareth",
  "Matmata",
  "Métouia",
  "Nouvelle Matmata",
];
export const kébili = [
  "Autres Villes",
  "Douz Nord",
  "Douz Sud",
  "Faouar",
  "Kébili",
  "Kébili Nord",
  "Kébili Sud",
  "Souk Lahad",
];
export const tozeur = [
  "Autres Villes",
  "Degache",
  "Hazoua",
  "Nefta",
  "Tameghza",
  "Tozeur",
];
export const tunis = [
  "Autres Villes",
  "Agba",
  "Ain Zaghouan",
  "Carthage",
  "Centre Urban Nord",
  "Centre Ville Lafayette",
  "Cité El Khadhra",
  "Cité Olympique",
  "Djebel Jelloud",
  "El Kabaria",
  "El Omrane",
  "El Omrane Supérieur",
  "El Ouardia",
  "Ettahrir",
  "Ezzouhour",
  "Hrairia",
  "Jardins De Carthage",
  "Laouina",
  "La Goulette",
  "La Marsa",
  "Lac 1",
  "Lac 2",
  "Le Bardo",
  "Le Kram",
  "Manar",
  "Médina",
  "Menzah",
  "Mutuelleville",
  "Séjoumi",
  "Sidi Bou Said",
  "Sidi Daoud",
  "Sidi El Bachir",
  "Sidi Hassine",
  "Tunis",
];
export const sidibouzid = [
  "Autres Villes",
  "Bir El Hafey",
  "Cebbala Ouled Asker",
  "Jilma",
  "Meknassy",
  "Menzel Bouzaiene",
  "Mezzouna",
  "Ouled Haffouz",
  "Regueb",
  "Sidi Ali Ben Aoun",
  "Sidi Bouzid",
  "Sidi Bouzid Est",
  "Sidi Bouzid Ouest",
  "Souk Jedid",
];
export const siliana = [
  "Autres Villes",
  "Bargou",
  "Bou Arada",
  "El Aroussa",
  "El Krib",
  "Gaafour",
  "Kesra",
  "Makthar",
  "Rouhia",
  "Sidi Bou Rouies",
  "Siliana",
  "Siliana Nord",
  "Siliana Sud",
];
export const jendouba = [
  "Autres Villes",
  "Ain Draham",
  "Balta Bou Aouane",
  "Bou Salem",
  "Fernana",
  "Ghardimaou",
  "Jendouba Nord",
  "Oued Meliz",
  "Tabarka",
];
